### Get all tasks
GET http://localhost:3000/tasks

### Create task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title" : "Clean my room",
  "description" : "Lots of cleaning has to be done"
}
