### Get all tasks
GET http://localhost:3000/tasks

### Get tasks with filter
GET http://localhost:3000/tasks?status=OPEN&search=hey

### Create task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title" : "Clean my room hey",
  "description" : "Lots of cleaning has to be done"
}

### Get a task
GET http://localhost:3000/tasks/a8bdadc5-0525-4d7e-a9c2-443eec013f76

### Delete a task
DELETE http://localhost:3000/tasks/76c21082-c595-4798-a2db-8275c0ce2971

### Update a task status
PATCH http://localhost:3000/tasks/a3a6a725-8405-44d2-b354-68ea275e057b/status
Content-Type: application/json

{
  "status" : "CLOSE"
}

################################################
### Sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username" : "sardor",
  "password" : "Secret@1"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username" : "sardor",
  "password" : "Secret@1"
}